#Build a Docker image and Push it to ACR
name: 'ACR'
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  ACR:
    name: 'Azure Login'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    runs-on: ubuntu-latest
    environment: dev
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: AzureContainerLogin
      uses: azure/docker-login@v1
      with:
        login-server: mytestacr007.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build . -t mytestacr007.azurecr.io/appdb:${{ github.sha }}
        docker push mytestacr007.azurecr.io/appdb:${{ github.sha }}
